### ISSUE TITLE
This file does not seem to be a valid module zip - 1.7.7.1

### ISSUE THREAD

**Issue by thierryzoller** [fraudlabspro/prestashop#1]
1. Downloaded Master
2. Install over "Upload Module"
3. Error "This file does not seem to be a valid module zip"

**Comment by fraudlabspro-com** [comment]
Please download the latest package from the [release area](https://github.com/fraudlabspro/prestashop/releases/latest).

**Comment by thierryzoller** [comment]
I used the link on your website, if that's the wrong one thats an issue

**Comment by fraudlabspro-com** [comment]
Thanks for the feedback. We have fixed the link on our website.
